### ISSUE TITLE
[Access Management] roles not shown

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/graviteeio-access-management#125]
i installed 1.3.0 AM
i created LDAP provider with role mapper
i activated enhance scope in client.

but when i get token or check token, i don't have new scope or new attribute in token?

how to do ?

Your Environment

Version used: 1.3.0

**Comment by tcompiegne** [comment]
Hi @vdelattre ,

Did you succeed to authenticate your user and get an access token ?

**Comment by vdelattre** [comment]
yes:
{
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6IndyaXRlIHJlYWQgZGVsZXRlIFZERSIsImFjdGl2ZSI6dHJ1ZSwiZXhwIjoxNTAwOTg1MDI5LCJ0b2tlbl90eXBlIjoiYmVhcmVyIiwianRpIjoiY2JiOTM2ZGMtODA1Zi00ZWYwLTk4NjktNmFlYjNkNDU5M2M1IiwiY2xpZW50X2lkIjoiVkRFIiwidXNlcm5hbWUiOiJ1aWQ9WEZSMjM0NzAwMSxvdT1BVUNIQU4tRlIsb3U9dXNlcnMsZGM9YXVjaGFuLGRjPWNvcnAifQ.LozSk_biT2Uy3Lem3H-3ejAc_1J3SteYUK-StFeVdladHA2AaH24NBu-_dDKpF1zbRDVNuRu_qy54C9BzXQWK_wet3E3p_vxhsIkVfwTO9VQeD7eqnFWkF_nc8fuuj35bE8e12Kt7P9P2UJ33RsXiN9TkJZBhPYOgk54BKuwUSmMrvWu0MgLiKOxo8zwnBUZDRMWZvQGg6mXhwFEv2RkK7HHVe4EVuvSfOKNF7ehJrsnit_HXlB3eOD1Vb76w56Uw5xHM1-O8KkflkU4w2EDMhZbuLD0FMJOu7oYSacn_zUFiylmTCVGXNEw9vp0UQznLkpfszRq1ABDQ7Shjv0LSQ",
    "token_type": "bearer",
    "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdGkiOiJjYmI5MzZkYy04MDVmLTRlZjAtOTg2OS02YWViM2Q0NTkzYzUiLCJzY29wZSI6IndyaXRlIHJlYWQgZGVsZXRlIFZERSIsImFjdGl2ZSI6dHJ1ZSwiZXhwIjoxNTAwOTg1MDI5LCJ0b2tlbl90eXBlIjoiYmVhcmVyIiwianRpIjoiNWU5ZTRmZTQtNWIzMy00YzU0LWE0MTctZWE3MjFlODcxNzVlIiwiY2xpZW50X2lkIjoiVkRFIiwidXNlcm5hbWUiOiJ1aWQ9WEZSMjM0NzAwMSxvdT1BVUNIQU4tRlIsb3U9dXNlcnMsZGM9YXVjaGFuLGRjPWNvcnAifQ.OPbtvqOyPxWuufdEYp-83HsImz2TKNgnTOxeaZ8VHjEKCa5D-Nrc4BDhx0bjyxngoEqDQ5sA30U3L15P4P9QVUowyCnpjT_wSbZReJO5nAVh9g6JOZl2ZhX-9HBM58tnLw-YaONPAJrJezQtV0sqAaQEqZZcj21v8rBKDgtiM-4lpAQEidMBZyzkBJZgstg3tmBlhAA_hnj7qrv8E2_yFGmUemORUPB6S6Bm7TEhH3wour-U8pu-TmY3cDvMFVdeUy4r5SFuOxAxOlqJzC9mCP3OIJTcuJk68eCIBhZJ2jTRunKBVrqU9XkAI0rrmCbZayIF-eSNHyNNRmE7Uc1LdQ",
    "expires_in": 1199,
    "scope": "write read delete VDE",
    "jti": "cbb936dc-805f-4ef0-9869-6aeb3d4593c5"
}

and in check token:
{
    "scope": "read VDE write delete",
    "active": true,
    "exp": 1500985029,
    "token_type": "bearer",
    "jti": "cbb936dc-805f-4ef0-9869-6aeb3d4593c5",
    "client_id": "VDE",
    "username": "uid=XFR2347001,ou=AUCHAN-FR,ou=users,dc=auchan,dc=corp"
}

i don't know how to add others fields than username

**Comment by tcompiegne** [comment]
Are `write read delete VDE` the default values registered with the client_id `VDE`?

For your second question we try to follow as much as possible the [RFC](https://tools.ietf.org/html/rfc7662#section-2.2), but you can retrieve user information by using the `UserInfoEndpoint` : 

`curl -X GET http://host/yourdomain/userinfo -H 'authorization: Bearer youraccesstoken'`

**Comment by vdelattre** [comment]
yes its default scope
it should add adminstrate

**Comment by tcompiegne** [comment]
Do you have access to the server logs ? in DEBUG mode, you should see the following line when you're requesting for a token : 

`15:43:41.715 [graviteeam-listener-26] DEBUG o.s.s.l.u.DefaultLdapAuthoritiesPopulator - Roles from search: [THE_USER_LDAP_GROUPS]'`

**Comment by vdelattre** [comment]
i don't find in log
i just found this:

16:58:11.171 [graviteeam-listener-18] [] DEBUG org.mongodb.driver.protocol.command - Command execution completed
16:58:11.172 [graviteeam-listener-18] [] DEBUG o.s.l.c.s.AbstractContextSource - Got Ldap context on server 'ldap://128.XXX:389/dc=auchan,dc=corp'
16:58:11.206 [graviteeam-listener-18] [] DEBUG o.s.l.c.s.AbstractContextSource - Got Ldap context on server 'ldap://128.XXXX:389/dc=auchan,dc=corp'
16:58:11.217 [graviteeam-listener-18] [] DEBUG o.s.ldap.core.LdapTemplate - The returnObjFlag of supplied SearchControls is not set but a ContextMapper is used - setting flag to true
16:58:11.217 [graviteeam-listener-18] [] DEBUG o.s.l.c.s.AbstractContextSource - Got Ldap context on server 'ldap://128.XXX:389/dc=auchan,dc=corp'
1

**Comment by tcompiegne** [comment]
Is it possible to request your LDAP via a tool like Apache Directory Studio ?

The request should be looking like this : 

**BaseDN** : your Base DN
**Search** : (uniqueMember=uid=XFR2347001,ou=AUCHAN-FR,ou=users,dc=auchan,dc=corp)

Can you tell me if the see some results ?

Thanks

**Comment by vdelattre** [comment]
with this query:
baseDn=cn=REFSITE,ou=applications,dc=auchan,dc=corp
search= (member=uid=XFR2347001,ou=AUCHAN-FR,ou=users,dc=auchan,dc=corp)

i have 1 response:
Dn:
cn=admin,cn=REFSITE,ou=applications,dc=auchan,dc=corp

**Comment by tcompiegne** [comment]
Ok, did you set *Subtree* scope for you LDAP query ?

**Comment by vdelattre** [comment]
no, but it's default value

**Comment by tcompiegne** [comment]
After many discussions and tests we can close this issue since it was due to LDAP configuration and better understanding about AM solution.
