### ISSUE TITLE
[global] role mapper for in-line identity provider

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/graviteeio-access-management#140]
I create a user inline provider with one user (test), and i want to associate role to this user.
but how to configure ?
i try uid=test, but it doesn't work.

how to configure also user mapper to have field in jwt ?

version= 1.3.0

**Comment by tcompiegne** [comment]
Hello @vdelattre,

Role mapping is not yet implementing for the in-line identity provider. I update the question issue to feature issue.
