### ISSUE TITLE
[oauth2] Scopes management

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/graviteeio-access-management#192]
Provide a better management of scope.

A scope must be composed of:
* id (technical)
* key (the key which is used to ask for a given scope during OAuth flow)
* name (human-readable name)
* description (human-readable description)

Name and description MAY be represented in multiple languages.
Tags for identifying language: https://tools.ietf.org/html/rfc5646

**Comment by tcompiegne** [comment]
closed since 365530e5c7bda5f1bdf216ab338c87e8e982a925.

We should create a new issue for the i18n support (scopes, html and email templates)
