### ISSUE TITLE
[oauth2] role mapping - scope lost in refresh token

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/graviteeio-access-management#231]
I have role mapping with ldap.
i have mapping:
memberOf=ADMIN => Administrator role (scope = administrate)
ou=AUCHAN-FR => role country_FR (scope = country_FR)

when i ask first token, i have all my scope: administrate and country_FR
when i refresh token : i lose scope administrate.

if i force user mapping: 
uid=XFR2347001 => role Administrator

when i refresh token, i don't lose scope administrate.

version used: 1.4.2

**Comment by tcompiegne** [comment]
Hi @vdelattre , you lost `country_FR` scope as well ?

**Comment by vdelattre** [comment]
hi @tcompiegne, no, when i refresh token, i don't lose scope country_FR

**Comment by vdelattre** [comment]
hello,
any news?

i think that in refresh token process, ldap group are not received (check) and so, mapping doesn't match

**Comment by tcompiegne** [comment]
Hi @vdelattre,

I made it :), that was a tricky bug to find !

The PR is ready : 

https://github.com/gravitee-io/graviteeio-access-management/pull/255

Should be available in the next AM release.
