### ISSUE TITLE
Echec lancement Gravitee AM

### ISSUE THREAD

**Issue by Vialloux** [gravitee-io/graviteeio-access-management#233]
Bonjour,

Lors de la commande `curl -L http://bit.ly/graviteeio-am | bash -s 8080` j'ai ce message d'erreur :
`Launch Gravitee.io Access Management ...
WARNING: The PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nginx.ports is invalid: Invalid port ":", should be [[remote_ip:]remote                                                                                                                                                             _port[-remote_port]:]port[/protocol]`

Avez-vous une idée du problème?

Je suis sur Debian 9

Merci

**Comment by brasseld** [comment]
I just had a try with latest docker and I do not meet such issue.
