### ISSUE TITLE
[oidc] Userinfo Endpoint path

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/graviteeio-access-management#286]
When moving from AM v1 to AM v2, the endpoint's path for userinfo has changed from

`/:securityDomain/userinfo` to `/:securityDomain/oauth/userinfo`

Any reason for this ?

**Comment by tcompiegne** [comment]
I don't know if we should specify protocol for each request, maybe someday an other protocol will use also an `userinfo` endpoint ...

Maybe we could set it to `/:securityDomain/oidc/userinfo`

**Comment by brasseld** [comment]
honestly, yes, I would prefer...
