### ISSUE TITLE
[oauth] Unable to authenticate a end-user

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/graviteeio-access-management#288]
Context: AM v2

When I'm providing bad credentials for an end-user, I'm receiving this response from the authorization server:

```
curl -X POST 'http://localhost:8092/portal/oauth/token?grant_type=password&scope=read&client_id=apim_portal&client_secret=3eab9968-052a-4a5d-ab99-68052ada5d0b&username=test&password=test2&scope=read'

{
  "error" : "invalid_grant"
}
```

Are you sure invalid_grant must be sent to the caller when the end-user can't be authenticated successfully ?

**Comment by tcompiegne** [comment]
Yes, according to the RFC : 

https://tools.ietf.org/html/rfc6749#section-5.2

invalid_grant
               The provided authorization grant (e.g., authorization
               code, **resource owner credentials**) or refresh token is
               invalid, expired, revoked, does not match the redirection
               URI used in the authorization request, or was issued to
               another client.
