### ISSUE TITLE
[oauth2] handle requested scopes allowed for the given resource owner

### ISSUE THREAD

**Issue by pletessier** [gravitee-io/graviteeio-access-management#307]
### Overview
According to (what I understand from) [rfc6749#section-3.3](https://tools.ietf.org/html/rfc6749#section-3.3), when you request an access token with a scope parameter, you should get a token valid for the requested scopes, if theses scopes are allowed for the given resource owner or client. I note that currently, a ressource owner can request any scopes he want.

### Configuration
AM gateway version master head 598b29c917fa6ab4c04fd7144a239cb40c8b762b
Linux OpenJDK 1.8
#### Identities :
```
{
  "id": "a15bf992-461c-457c-9bf9-92461c157cf6",
  "name": "inline",
  "type": "inline-am-idp",
  "configuration": "{\"users\":[{\"firstname\":\"Tom\",\"lastname\":\"Cat\",\"username\":\"tom\",\"password\":\"tom\"},{\"firstname\":\"Jerry\",\"lastname\":\"Mouse\",\"username\":\"jerry\",\"password\":\"jerry\"}]}",
  "mappers": {},
  "roleMapper": {
    "482e139f-56bc-466d-ae13-9f56bcc66de5": [
      "username=jerry"
    ]
  },
  "domain": "domain",
  "external": false,
  "createdAt": 1535640134641,
  "updatedAt": 1535640415642
}
```
#### Roles : 
```
[
  {
    "id": "a126b0e6-14b8-43a3-a6b0-e614b803a3f6",
    "name": "Cat",
    "description": "",
    "domain": "domain",
    "permissions": [
      "catch"
    ],
    "createdAt": 1535640261693,
    "updatedAt": 1535640265665
  },
  {
    "id": "482e139f-56bc-466d-ae13-9f56bcc66de5",
    "name": "Mouse",
    "domain": "domain",
    "permissions": [
      "escape"
    ],
    "createdAt": 1535640277178,
    "updatedAt": 1535640279588
  }
]
```

#### Actual
```
bash-4.4$ http POST "http://localhost:8092/domain/oauth/token" grant_type==password client_id==clientId client_secret==clientSecret scope=='openid run catch' username==tom password==tom
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Length: 452
Content-Type: application/json
Pragma: no-cache

{
    "access_token": "9a1e6c46-65a2-44a0-9e6c-4665a214a0ec",
    "expires_in": 7199,
    "id_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b20iLCJhdWQiOiJjbGllbnRJZCIsImlzcyI6Imh0dHA6Ly9ncmF2aXRlZS5hbSIsImV4cCI6MTUzNTY1NTQwOCwiaWF0IjoxNTM1NjQxMDA4fQ.C-Du7RR2xs-NansWf-Kku5VCXmtm_7t806LtICwlkw7D5fHwm1DnTqrtXNt8RB19WHR3dGRl02PzgumF6RY8Kg",
    "refresh_token": "99fd62ee-47d2-4264-bd62-ee47d202641d",
    "scope": "openid run catch",
    "token_type": "bearer"
}
```
#### Expected 
Note the missing "run" scope : 

```
bash-4.4$ http POST "http://localhost:8092/domain/oauth/token" grant_type==password client_id==clientId client_secret==clientSecret scope=='openid run catch' username==tom password==tom
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Length: 452
Content-Type: application/json
Pragma: no-cache

{
    "access_token": "9a1e6c46-65a2-44a0-9e6c-4665a214a0ec",
    "expires_in": 7199,
    "id_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b20iLCJhdWQiOiJjbGllbnRJZCIsImlzcyI6Imh0dHA6Ly9ncmF2aXRlZS5hbSIsImV4cCI6MTUzNTY1NTQwOCwiaWF0IjoxNTM1NjQxMDA4fQ.C-Du7RR2xs-NansWf-Kku5VCXmtm_7t806LtICwlkw7D5fHwm1DnTqrtXNt8RB19WHR3dGRl02PzgumF6RY8Kg",
    "refresh_token": "99fd62ee-47d2-4264-bd62-ee47d202641d",
    "scope": "openid catch",
    "token_type": "bearer"
}
```

### Proposed solution
Replace [`Set<String> enhanceScopes = new HashSet<>(accessToken.getScopes());`](https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java#L131)
by `Set<String> enhanceScopes = new HashSet<>();`

And add a line `accessToken.getScopes().add(OPEN_ID);` in [TokenEnhancerImpl::enhanceIDToken(...)](https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java#L183)

**Comment by pletessier** [comment]
Hi @brasseld ,
I'm ready for a PR if you confirm the bug !

**Comment by brasseld** [comment]
Sorry, I was thinking that I told you it was a bug....

**Comment by pletessier** [comment]
Another related problem not solved by my changes is : if enhanceScopes is true, and resource owner has no roles, I think he shouldn't be granted any other scopes than "openid", right ?
Currently, it also returns all the requested scopes.

**Comment by brasseld** [comment]
LGTM

**Comment by tcompiegne** [comment]
Hi @pletessier,

As a matter of fact, the authorized scopes processing is done here : 

https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/TokenRequestResolver.java#L46

and here : 

https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolver.java

You can see that a `TODO` about user permissions checking : 

https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolver.java#L72 

Still I did not have the time to do the job but it is in my TODO List.

**Comment by pletessier** [comment]
Ok @tcompiegne, thanks for the explanations !
I don't want to hurry you, but do you have a planned release for this TODO ?

**Comment by tcompiegne** [comment]
The next release (2.1.0) will be focus on OpenID Connect Certification, I will see if we can include this issue as well.

**Comment by pletessier** [comment]
Nice ! Hang in there !
I'm here to test if I can help !
