### ISSUE TITLE
Use login of a third party oauth2 server

### ISSUE THREAD

**Issue by rlvillacarlos** [gravitee-io/graviteeio-access-management#326]
Hi I would like to know how to make garvitee use the existing login page of an existing thrid party oauth2 server. I cannot seem to find an example of it in the documentation. 

What I want to be able to do is to use the oauth2 login page for SSO.

**Comment by tcompiegne** [comment]
Hi @rlvillacarlos,

What is your use case ? You want to login to Gravitee.io API Management or Access Management ?

Regards

**Comment by tcompiegne** [comment]
I'm closing this issue because it has been inactive for a few days.

Please reopen if you still encounter this issue.

Thanks
