### ISSUE TITLE
Token Endpoint for other security domains

### ISSUE THREAD

**Issue by AmreeshTyagi** [gravitee-io/graviteeio-access-management#348]
I am not able to create token using `http://localhost:8093/admin/token` for my other domain `demo.com`
I have tried with `http://localhost:8093/demo.com/token` but no luck. :(

I am referring [Token endpoint](https://docs.gravitee.io/am/2.x/am_management_api_documentation.html#token_endpoint) , so that I can create users using this token.

Please help me to solve this issue.

**Comment by tcompiegne** [comment]
Hi @AmreeshTyagi,

The Token endpoint you mention is for the Management part (http port `8093`) of Access Management. It's only available for the default admin domain.

https://docs.gravitee.io/am/2.x/am_installguide_mgt_api.html

To create OAuth 2.0 tokens please use the Authorization server part (http port `8092`) of Access Management.

https://docs.gravitee.io/am/2.x/am_installguide_gateway.html

If you use the latest version, protocol endpoints are registered here : 

`http://localhost:8092/demo.com/oidc/.well-known/openid-configuration`

**Comment by AmreeshTyagi** [comment]
Thanks @tcompiegne . It means I can't use management APIs for another security domain.
Then, how can I create user for a specific domain (demo.com) using API.

I have tried to create user with admin/token, but it was giving me error 501 `Not Implemented`

Step 1: POST request to http://localhost:8093/admin/token with basic authentication (admin/adminadmin) & received access_token:
`{
    "access_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJBZG1pbmlzdHJhdG9yIiwiZmFtaWx5X25hbWUiOiIifQ.n0EgQUc6XMQyMHIM0jrMrPNOP-YqCxGJbPAbR5P9g3Bz8WnjzDNuMv4g9SK1fPtcPTLmbxWZDyP1hV9vjdsLdA",
    "expires_at": "Mon Oct 08 18:25:57 IST 2018",
    "token_type": "bearer"
}`

Step 2. POST request to `http://localhost:8093/management/domains/demo.com/users` to create user

Giving me error `501 Not Implemented`

Please let me know, if I am doing anything wrong.

**Comment by tcompiegne** [comment]
Currently you have to use `Identity provider` to manage your users : 

https://docs.gravitee.io/am/2.x/am_userguide_create_identity_provider.html
https://docs.gravitee.io/am/2.x/management-api/index.html (create an identity provider)

For example if you want to create `In memory users` for the `demo.com` domain,  you can call the following request : 

```
curl -H "Authorization: Bearer :accessToken" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X POST \
     -d '{
           "type": "inline-am-idp",
           "name": "Inline IdP",
           "configuration": "{\"users\":[{\"firstname\":\"johndoe\",\"lastname\":\"John\",\"username\":\"Doe\",\"password\":\"johndoepassword\"}]}"
         }' \
     http://localhost:8093/management/domains/demo.com/identities
```

Is that clearer to you ?

**Comment by tcompiegne** [comment]
Currently identity providers are the only way to manage your users. Bind to your client application, identity provider's users will be able to login and ask tokens to access protected resources (such as APIs)

https://docs.gravitee.io/am/2.x/am_quickstart_authenticate_users.html

For your information, the issue #145 has been created quite a while ago to enable users creation directly from Access Management but still no time to do it.

**Comment by tcompiegne** [comment]
I'm closing this issue because it has been inactive for a few days.

Please reopen if you still encounter this issue.

Thanks

**Comment by AmreeshTyagi** [comment]
Sure. Thanks. Waiting for feature request #145 .
