### ISSUE TITLE
How to create user to existing identity provider

### ISSUE THREAD

**Issue by WLun001** [gravitee-io/graviteeio-access-management#459]
As the documentation shown, this will create a new identify provider for every call, https://docs.gravitee.io/am/2.x/am_quickstart_authenticate_users.html. 

How to add new user to existing identify provider?

**Comment by tcompiegne** [comment]
Hi @WLun001 ,

If you use Inline Provider, you just have to click on 'Add User` of your existing inline provider to create a new user.

![Inline Provider](https://docs.gravitee.io/images/am/2.x/graviteeio-am-quickstart-create-idp.png)

**Comment by WLun001** [comment]
Hi @tcompiegne 
How to add through API instead of UI?

**Comment by tcompiegne** [comment]
Currently with the Inline Provider you have to send all users in the body request (there is no "PATCH" action, you have to set all your users for each update) : 

So to update your existing Inline Provider, you can send this request :

```
curl -H "Authorization: Bearer :accessToken" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X POST \
     -d '{
           "configuration": "{\"users\":[{\"firstname\":\"John\",\"lastname\":\"Doe\",\"username\":\"johndoe\",\"password\":\"johndoepassword\"}, {\"firstname\":\"John2\",\"lastname\":\"Doe2\",\"username\":\"johndoe2\",\"password\":\"johndoepassword2\"},
{\"firstname\":\"John3\",\"lastname\":\"Doe\",\"username\":\"johndoe3\",\"password\":\"johndoepassword3\"}]}",
           "name": "Inline IdP"
         }' \
     http://GRAVITEEIO-AM-MGT-API-HOST/management/domains/:securityDomainPath/identities/[identityId]
```

Gravitee.io AM 2.2 (mid January 2019) will come with a complete User Management with "standards" CRUD operations : 

```
GET|POST|PUT|DELETE http://GRAVITEEIO-AM-MGT-API-HOST/management/domains/:securityDomainPath/users
```
