### ISSUE TITLE
Dockerfile for management-api exposing wrong port ?

### ISSUE THREAD

**Issue by BrtCst** [gravitee-io/graviteeio-access-management#481]
Hello,

The dockerfile for management-api (graviteeio-access-management/docker/management-api/Dockerfile) is exposing port 8092. Shouldn’t it be 8093 ?

The log of the container :
[graviteeio-node] [] INFO  i.g.a.m.jetty.JettyHttpServer - HTTP Server is now started and listening on port 8093

Regards.

**Comment by brasseld** [comment]
:( :( :( :(

You're right.....

May I ask you to provide a PR to fix it ?

**Comment by BrtCst** [comment]
I'm doing it now.
