### ISSUE TITLE
[Cors] openid-configuration URL has been blocked by CORS policy

### ISSUE THREAD

**Issue by philippej13** [gravitee-io/graviteeio-access-management#484]
Steps to reproduce with a sample project of the "angular-oauth-oidc" project:

- git clone https://github.com/manfredsteyer/angular-oauth2-oidc.git 
- modify the file "projects/sample/src/app/auth.config.ts" with:
   - changing the value of the issuer (oidc endpoint, for me it is : http://192.168.1.4:8092/auth/domain1/oidc) and the clientId
   - adding some parameters: 
       - skipIssuerCheck: true,
       - requireHttps: false,
       - strictDiscoveryDocumentValidation: false 

- npm install
- ng serve
- navigate to http://localhost:4200 and click on the login button

--> Message in chrome : 
`Access to XMLHttpRequest at 'http://192.168.1.4:8092/auth/domain1/oidc/.well-known/openid-configuration' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by tcompiegne** [comment]
Closed by 9c9add6b9c0a6c8e5e9a0359d2e0161c504c9cdd
