### ISSUE TITLE
HTTP ERROR 404

### ISSUE THREAD

**Issue by rotparmna** [gravitee-io/graviteeio-access-management#495]
Good afternoon, when installing and uploading services according to the guide, it is not working for me to access UI.

Error 404 (image) --> https://drive.google.com/open?id=10En_WNZhJHHjhRHn89WIvQqwKlaYc5dD

**constants.json**
```
{
  "portalTitle": "Access Management",
  "baseURL": "http://localhost:8093/management",
  "authentication": {
    "domainId": "admin",
    "authorize": "http://localhost:8093/admin/authorize",
    "redirectUri": "http://localhost:4200/login/callback",
    "logoutUri": "http://localhost:8093/admin/logout?target_url=http://localhost:4200/logout/callback"
  }
}
```

**nginx.conf**
```
server {
        listen       4200;
        server_name	 my-app;
		
		index index.html;

		root gravitee-am-webui-2.1.1;

		location / {
			try_files $uri $uri/ /index.html;
		}
    }
```

**Comment by brasseld** [comment]
You are probably hitting this issue: https://github.com/gravitee-io/graviteeio-access-management/issues/488

**Comment by rotparmna** [comment]
> You are probably hitting this issue: #488

Thanks for answering, but what should I do to solve the issue?

**Comment by tcompiegne** [comment]
Waiting for the AM 2.2 :) (scheduled for today)

**Comment by tcompiegne** [comment]
Hi @rotparmna,

It seems that your `admin` domain has been misconfigured ... can you show me the result of these following mongoDB commands : 

```
$ mongo
$ use gravitee-am
$ db.domains.findOne({'_id' : 'admin'})
```
Regards

**Comment by rotparmna** [comment]
> Hi @rotparmna,
> 
> It seems that your `admin` domain has been misconfigured ... can you show me the result of these following mongoDB commands :
> 
> ```
> $ mongo
> $ use gravitee-am
> $ db.domains.findOne({'_id' : 'admin'})
> ```
> Regards

Result

`_id
:
"admin"
createdAt
:
2019-01-11 15:53:45.323
description
:
"AM Admin domain"
enabled
:
true
master
:
true
name
:
"admin"
path
:
"admin"
updatedAt
:
2019-01-11 15:58:38.607`

**Comment by tcompiegne** [comment]
Ok so admin's `identities` is missing ..., did you update the domain configuration ? do you have some identity provider in the MongoDB `identities` collection ?

```
$ mongo
$ use gravitee-am
$ db.identities.find()
```

**Comment by rotparmna** [comment]
> Ok so admin's `identities` is missing ..., did you update the domain configuration ? do you have some identity provider in the MongoDB `identities` collection ?
> 
> ```
> $ mongo
> $ use gravitee-am
> $ db.identities.find()
> ```

Thanks @tcompiegne ... Result for identities

`{"_id":"70924266-00f0-4e0a-9242-6600f0ae0ab6","configuration":"{\"users\":[{\"firstname\":\"Administrator\",\"lastname\":\"\",\"username\":\"admin\",\"password\":\"adminadmin\"}]}","createdAt":"2019-01-11T15:53:46.503Z","domain":"admin","external":false,"mappers":{},"name":"Inline users","roleMapper":{},"type":"inline-am-idp","updatedAt":"2019-01-11T15:53:46.503Z"}`

**Comment by tcompiegne** [comment]
Can you update your domain and tell me if it works : 

```
db.domains.update(
   { '_id': 'admin' },
   { $set:
      {
        identities: [ "70924266-00f0-4e0a-9242-6600f0ae0ab6" ]
      }
   }
)
```

**Comment by rotparmna** [comment]
> Can you update your domain and tell me if it works :
> 
> ```
> db.domains.update(
>    { '_id': 'admin' },
>    { $set:
>       {
>         identities: [ "70924266-00f0-4e0a-9242-6600f0ae0ab6" ]
>       }
>    }
> )
> ```

Thanks, but no work :( .... Result domains

`{"_id":"admin","createdAt":"2019-01-11T15:53:45.323Z","description":"AM Admin domain","enabled":true,"master":true,"name":"admin","path":"admin","updatedAt":"2019-01-11T15:58:38.607Z","identities":["70924266-00f0-4e0a-9242-6600f0ae0ab6"]}`

Also, from postman I make a request to the URL _http://localhost:8093/admin/token_, with the authentication data (admin, adminadmin), and I return **500 Server Error**, with header response:

> X-Content-Type-Options →nosniff
> X-XSS-Protection →1; mode=block
> Pragma →no-cache
> X-Frame-Options →DENY
> Cache-Control →must-revalidate,no-cache,no-store
> Content-Type →text/html;charset=iso-8859-1
> Connection →close

**Comment by rotparmna** [comment]
> Can you update your domain and tell me if it works :
> 
> ```
> db.domains.update(
>    { '_id': 'admin' },
>    { $set:
>       {
>         identities: [ "70924266-00f0-4e0a-9242-6600f0ae0ab6" ]
>       }
>    }
> )
> ```

**Its work** @tcompiegne thanks a lot

**Comment by rotparmna** [comment]
When would version 2.2.0 be in production?

**Comment by tcompiegne** [comment]
Hi @rotparmna ,

It's out just now :) 

https://download.gravitee.io/graviteeio-am/
