### ISSUE TITLE
[oauth2] CORS issue when invoking check_token endpoint from browser

### ISSUE THREAD

**Issue by tomsawyers** [gravitee-io/graviteeio-access-management#67]
We have an error with the Check token. 

The server rejects the OPTIONS query sent by the browser to inform the server that the next request contains a HEADER AUTHORIZATION.

Response: 
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

You will find the traces of the error in the following file :
[Check_ToKEN_Error.docx](https://github.com/gravitee-io/graviteeio-access-management/files/988988/Check_ToKEN_Error.docx)

**Comment by tcompiegne** [comment]
Hi @tomsawyers ,

Can you tell me more about your scenario ? By calling the check token endpoint you expose to everyone your client secret (stored inside your javascript source code) which is very bad.

Thanks

**Comment by tomsawyers** [comment]
Hi @tcompiegne,
 
This check token will potentially be used by some APIs to validate the token of the calling client. 
These APIs will make an additional check token to that made by the API manager.
And it is possible that the API is protected by the authorization server but not managed by the API manager. Hence the need for a check token.

Thanks
