### ISSUE TITLE
GateWay get Acces_Token and access to api resource it's don's not work

### ISSUE THREAD

**Issue by lewis-ing** [gravitee-io/graviteeio-access-management#68]
GateWay get Acces_Token and access to api resource it's don's not work

**Comment by brasseld** [comment]
Hi @lewis-ing,

I'm sorry but I don't understand.
Can you tell us what's going wrong exactly?

**Comment by lewis-ing** [comment]
@brasseld Please reader My doc.
[GT_Access_Token.docx](https://github.com/gravitee-io/graviteeio-access-management/files/1001353/GT_Access_Token.docx)

**Comment by brasseld** [comment]
Ok, I have a better understanding now. you are mix-in Gravitee.io AM with Gravitee.io APIM and check access_token from the OAuth2 policy.

So, according to me, your resource configuration is not correct, you must have something like this:
AM Server URL: http://localhost:8092/
Security domain: admin
Client Id: admin
Client Secret: admin-secret

Please give us your feedback.

**Comment by lewis-ing** [comment]
Thanks @brasseld,I have tried it and It's Ok.
