### ISSUE TITLE
[management-ui] Can't access the Domain menu 

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/graviteeio-access-management#79]
Hello,

The Domain menu does not load.
See below:

![image](https://cloud.githubusercontent.com/assets/9626829/26252837/a5af0ede-3cb1-11e7-9d99-515e84a3fb0c.png)

Each time we click the Domain menu, it finishes with timeout.
In the gateway logs, we can see that:

![image](https://cloud.githubusercontent.com/assets/9626829/26252853/ad5eea6e-3cb1-11e7-9ef9-958288eeb8d4.png)

Gateway JVM is configured with HTTP proxy to reach the Internet.

**Comment by brasseld** [comment]
Why the JVM is configure to reach Internet ?

**Comment by bcollard** [comment]
the AM is on a public domain. 
THe same domain is used for /management & /admin & /custom-domain & the management UI

**Comment by brasseld** [comment]
I did not get you. Gateway itself does not have to access to the Internet! I don't understand why you need such access.

**Comment by bcollard** [comment]
My bad, I put the proxy on HTTP and not on HTTPS.
And yes, the gateway need to hit https://<DOMAIN NAME>/management/domains , so the gateway needs to reach the Internet in my case.

**Comment by bcollard** [comment]
It works now. We can close the ticket.
Thank you for your support.
