### ISSUE TITLE
gravitee access management : unexpected redirection after login

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/graviteeio-access-management#81]
Dear all,

When using oauth2 authorization code flow, a successfull login leads to the grant of an authorization code, given as a query param in the redirect url.

### Expected Behavior
I thought the authorization code would be given directly in the http response to the login submit (in the 302 response to the http post).

### Current Behavior
The login page submit redirects to the /authorize endpoint, and this one gives the authorization code.
I don't know if this is normal behaviour.

### Possible Solution
If this behaviour is not intended, maybe alternatively the login page could itself compute the authorization code and give it in its response ?

### Steps to Reproduce (for bugs)

1. call /authorize, it redirects to the /login
2. submit credentials, which are sent back to /login because of the custom html login form, containing : 
`<form method="post" th:action="@{/login}">`
3. the post gives a 302 to /authorize
4. the authorize endpoint give the authorization code

### Context
This is a bit annoying in the context of a webview in a mobile native app because the submit response does not contain the authorization code. So the native app has to do the redirection programmatically. If the behaviour is normal we will do it, but we fear we misconfigured the server.

### Your Environment

* Version used: 1.5
* Browser Name and version: Chrome
* Operating System and version: Windows

Thanks,
Anselme

**Comment by brasseld** [comment]
Please have a look to: https://developers.google.com/identity/protocols/OAuth2InstalledApp#step-2-send-a-request-to-googles-oauth-20-server

**Comment by tcompiegne** [comment]
Hello @AnselmeDewavrin 

Can we close this issue ?

**Comment by tcompiegne** [comment]
Closed since no feedback
