### ISSUE TITLE
[admin] password admin

### ISSUE THREAD

**Issue by geraudmasson** [gravitee-io/graviteeio-access-management#96]
Hi,

I would like to know how to change the password of the user admin for the connexion to the webUi of the access management

Cheers

**Comment by tcompiegne** [comment]
Hi @geraudmasson,

You can do it via the UI. You choose the `admin` domain, go to identity provider list and edit the `Inline users` identity provider to modify the `admin` user.

**Comment by tcompiegne** [comment]
Hi @geraudmasson,

Can we close this issue ?

**Comment by brasseld** [comment]
Please add documentation to change admin user.

**Comment by geraudmasson** [comment]
Tks, it works :) 
Issue closed
